// let num1=120;
// let num2=100;
// let add= num1+num2;
// let sub= num1-num2;
// let mul= num1*num2;
// let div= num1/num2;
// console.log(add);
// console.log(sub);
// console.log(mul);
// console.log(div);
let name="Ashok kumar";
let age="22";
let clg="USBM";
let city="BBSR";
let batch="2025";
let text ='My name is ${name} , ${age} , city:{clg}!';
console.log(text);
